name: Sync Chart Deleted
on:
  repository_dispatch:
    types:
      - chart-deleted
  workflow_dispatch:
    inputs:
      chart:
        description: 'Chart name'
        required: true
        type: string
      version:
        description: 'Chart version'
        required: true
        type: string

jobs:
  build-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CHART_NAME: ${{ github.event.client_payload.chart || github.event.inputs.chart }}
      CHART_VERSION: ${{ github.event.client_payload.version || github.event.inputs.version }}

    steps:
      - name: Set up Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
        id: go
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.KUADRANT_DEV_PAT }}
          fetch-depth: 0
      - name: Delete chart package
        working-directory: ${{ github.workspace }}
        run: |
          make delete-chart \
            CHART_NAME="${{ env.CHART_NAME }}" \
            CHART_VERSION="${{ env.CHART_VERSION }}"
      - name: Update local index
        run: |
          make helm-index
      - name: Commit the changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add charts
          git commit -m "Sync deleted chart ${{ env.CHART_NAME }} version ${{ env.CHART_VERSION }}"
          git push
