on:
  repository_dispatch:
    types:
      - sync-chart

jobs:
  build-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Set up Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
        id: go
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get chart package
        working-directory: ${{ github.workspace }}
        run: |
          make get-chart \
            BROWSER_DOWNLOAD_URL="${{ github.event.client_payload.browser_download_url }}" \
            CHART_NAME="${{ github.event.client_payload.chart }}" \
            CHART_VERSION="${{ github.event.client_payload.version }}"
